# Generated by Django 5.2.10 on 2026-01-09 22:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('summary', models.TextField()),
                ('target_audience', models.TextField()),
                ('primary_problem', models.TextField()),
                ('constraints', models.JSONField(default=list)),
                ('brand_voice', models.TextField(blank=True, null=True)),
                ('success_definition', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.TextField()),
                ('title', models.TextField()),
                ('objective', models.TextField()),
                ('problem_statement', models.TextField()),
                ('deliverables', models.JSONField(default=list)),
                ('requirements', models.JSONField(default=dict)),
                ('evaluation_criteria', models.JSONField(default=list)),
                ('tone_rules', models.JSONField(default=list)),
                ('source_answers', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
