# Generated by Django 5.2.10 on 2026-01-10 02:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_category', models.CharField(db_index=True, max_length=100)),
                ('suggested_tool_or_skill', models.CharField(max_length=255)),
                ('reason_for_suggestion', models.TextField()),
                ('learning_resource_link', models.URLField()),
                ('is_optional', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='brand_voice',
        ),
        migrations.RemoveField(
            model_name='client',
            name='primary_problem',
        ),
        migrations.RemoveField(
            model_name='project',
            name='evaluation_criteria',
        ),
        migrations.RemoveField(
            model_name='project',
            name='problem_statement',
        ),
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='communication_style',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='decision_style',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='dislikes',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='client',
            name='industry',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='preferences',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='client',
            name='primary_need',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='what_they_do',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='approval_log',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='basic_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='client_criteria',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='project',
            name='evaluation_criteria_creative',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='evaluation_criteria_technical',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='resources_excluded',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='resources_provided',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='scope_excluded',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='scope_included',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROGRESS', 'In Progress'), ('DELIVERED', 'Delivered'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='subcategory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='user_defined_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='target_audience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='UserSkillProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skills', models.JSONField(default=list)),
                ('skill_level', models.CharField(choices=[('BASIC', 'Basic'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], max_length=20)),
                ('preferred_tools', models.JSONField(default=list)),
                ('excluded_tools', models.JSONField(default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
