# Generated by Django 5.2.10 on 2026-01-10 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_learningoption_remove_client_brand_voice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROGRESS', 'In Progress'), ('DELIVERED', 'Delivered'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('GENERATING', 'Generating'), ('FAILED', 'Failed')], db_index=True, default='DRAFT', max_length=20),
        ),
    ]
