import json
import logging
from pathlib import Path
from django.conf import settings
from rest_framework import viewsets, status
from rest_framework.decorators import api_view, action
from rest_framework.response import Response
from .models import Project, Client
from .serializers import ProjectSerializer, ClientSerializer
from .llm import LLMService

logger = logging.getLogger('api')

@api_view(["GET"])
def health(request):
    return Response({"status": "ok"})

@api_view(["GET"])
def questionnaire_config(request):
    config_path = settings.BASE_DIR / "config" / "questionnaire.json"
    try:
        with open(config_path, "r") as f:
            data = json.load(f)
        return Response(data)
    except FileNotFoundError:
        return Response({"error": "Configuration file not found"}, status=500)
    except json.JSONDecodeError:
        return Response({"error": "Invalid configuration file"}, status=500)

class ProjectViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = Project.objects.all()
    serializer_class = ProjectSerializer

    @action(detail=False, methods=['post'])
    def generate(self, request):
        category = request.data.get("category")
        answers = request.data.get("answers")

        if not category or not answers:
            return Response(
                {"error": "Category and answers are required"}, 
                status=status.HTTP_400_BAD_REQUEST
            )

        # 1. Call Service (Stub)
        service = LLMService()
        try:
            client_data, project_data = service.generate_project(category, answers)
        except Exception as e:
            logger.error("Error generating project", exc_info=True)
            return Response(
                {"error": f"Generation failed: {str(e)}"},
                status=status.HTTP_500_INTERNAL_SERVER_ERROR
            )

        # 2. Persist Data
        # Save Client
        client = Client.objects.create(**client_data)

        # Save Project
        # Ensure project_data uses the client instance
        # Remove 'category' from project_data if it's not generated by LLM, 
        # or ensure LLM generates it. Our stub generates it in project_data.
        
        # In our model, 'client' is a ForeignKey.
        project = Project.objects.create(client=client, **project_data)

        # 3. Serialize and Return
        serializer = ProjectSerializer(project)
        return Response(serializer.data, status=status.HTTP_201_CREATED)
